name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ ./Tests/test1.cpp -o ./test1
        command: "./test1"
        input: |-
          14
          5
          7
          3
        expected-output: 5 3
        comparison-method: contains
        timeout: 1
        max-score: 3
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ ./Tests/test2.cpp -o ./test2
        command: "./test2"
        input: ''
        expected-output: 1 1 5040
        comparison-method: contains
        timeout: 1
        max-score: 3
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ ./Tests/test3.cpp -o ./test3
        command: "./test3"
        input: ''
        expected-output: 0.1 1 0.166667
        comparison-method: contains
        timeout: 1
        max-score: 3
    - name: Test 4
      id: test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 4
        setup-command: g++ ./Tests/test4.cpp -o ./test4
        command: "./test4"
        input: |-
          7
          2
          n
        expected-output: |-
          Probability of winning is 0.0476
          Odds of winning are 1 in 21
        comparison-method: contains
        timeout: 1
        max-score: 3
    - name: Test 5
      id: test-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 5
        setup-command: g++ ./Tests/test5.cpp -o ./test5
        command: "./test5"
        input: |-
          12
          1
          n
        expected-output: |-
          Probability of winning is 0.0833
          Odds of winning are 1 in 12
        comparison-method: contains
        timeout: 1
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
        TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
      with:
        runners: test-1,test-2,test-3,test-4,test-5
